apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-tc
  labels:
    app: myapp
    tier: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
