Vagrant.configure("2") do |config|
  # Define the master node
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "master-node"
    master.vm.network "private_network", type: "dhcp"
    master.vm.provider "virtualbox" do |v|
      v.memory = 2046
      v.cpus = 2
    end

    master.vm.provision "shell", inline: <<-SCRIPT
      # Install Kubernetes on the master node
      sudo apt-get update
      sudo apt-get install -y docker.io
      sudo apt-get install -y apt-transport-https curl
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      sudo apt-mark hold kubelet kubeadm kubectl
      sudo kubeadm init --pod-network-cidr=192.168.0.0/16
      kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      kubectl taint nodes --all node-role.kubernetes.io/master-
      sudo sh -c 'kubeadm token create --print-join-command > /vagrant/kubeadm_join_command.sh'
    SCRIPT
  end

  # Define worker nodes
  (1..2).each do |index|
    config.vm.define "worker#{index}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "worker-node-#{index}"
      node.vm.network "private_network", type: "dhcp"
      node.vm.provider "virtualbox" do |v|
        v.memory = 2046
        v.cpus = 2
      end

      node.vm.provision "shell", inline: <<-SCRIPT
        # Install Kubernetes on the worker node
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo apt-get install -y apt-transport-https curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubelet kubeadm kubectl
        sudo apt-mark hold kubelet kubeadm kubectl
        sudo sh /vagrant/kubeadm_join_command.sh
      SCRIPT
    end
  end
end
